---
# tasks file for ansible-role-cvmfs
#
- name: get_url the CVMFS repo
  get_url:
    url: http://cvmrepo.web.cern.ch/cvmrepo/yum/cernvm.repo
    dest: /etc/yum.repos.d/cernvm.repo
    mode: 0644
  register: cvmfs_cernrepo
  ignore_errors: True

- name: rpm_key CVMFS gpg key
  rpm_key:
    key: http://cvmrepo.web.cern.ch/cvmrepo/yum/RPM-GPG-KEY-CernVM
    state: present
  register: cvmfs_cernrepokey

- name: copy in cernvm.repo if get_url from cvmrepo.web.cern.ch fails
  copy:
    src: cernvm.repo
    dest: /etc/yum.repos.d/cernvm.repo
    mode: 0644
  when: cvmfs_cernrepo|failed

#TODO?
#- name: add a cernkey if cvmfs_cernrepokey failed
#  rpm_key: src=cernvm.repo dest=/etc/yum.repos.d/cernvm.repo mode=0644
#  when: cvmfs_cernrepo.failed
#

- name: Check if fgci-release7 is installed
  yum:
    pkg: fgci-release7
    state: installed
  register: reg_cvmfs_fgci7_installed
  check_mode: no
  ignore_errors: True

- name: Install FGCI repo (fgci-release7) if it is not
  yum:
    pkg: http://idris.fgi.csc.fi/fgci7/x86_64/fgci/rpms/fgci-release7-1-1.el7.noarch.rpm
  when: 
    - ansible_distribution_major_version == "7" 
    - fgci_install == True 
    - reg_cvmfs_fgci7_installed|failed

- name: Install FGCI CVMFS repofiles
  yum:
    name: cvmfs-repofiles-fgi
    state: present
  when: fgci_install == True

- name: Install CVMFS client EL6
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "cvmfs-release"
    - "cvmfs-keys"
    - "cvmfs"
    - "cvmfs-init-scripts"
    - "cvmfs-auto-setup"
  when: ansible_distribution_major_version == "6"

- name: Install CVMFS client EL7
  yum:
    name: "{{ item }}" 
    state: present
  with_items:
    - "cvmfs-keys"
    - "cvmfs"
    - "cvmfs-config-default"
    - "autofs"
  when: ansible_distribution_major_version == "7"
